[package]
name = "encrypted-file-access"
version = "0.1.0"
edition = "2021"
authors = ["ccyuen1"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
tempfile = "3.10.1"
